version: "3.8"

services:
  myjenkins:
    container_name: my_challenge_jenkins
    image: jenkins/jenkins:lts
    user: root
    environment:
      MY_NAME: "bernydesh"
      # Gmail extra configuration for mailer plugin
      JAVA_OPTS: "-Djava.awt.headless=true -Dmail.smtp.starttls.enable=true"
    ports:
      - "8080:8080"
    volumes:
      # Named  Docker volume details at the bottom
      - jenkins_home:/var/jenkins_home
      # WARNING:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - net_jenkins_challenge
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 2G

# To use docker-volume (custom_jenkins_home) instead of a directory path-file
volumes:
  jenkins_home:
    name: "my_challenge_jenkins_home"

networks:
  net_jenkins_challenge:
    driver: bridge
    name: net_jenkins_challenge
